apiVersion: v1
kind: Service
metadata:
  name: botcrew-redis
  namespace: {{ .Values.namespace }}
  labels:
    app: botcrew-redis
    {{- include "botcrew.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
      protocol: TCP
      name: redis
  selector:
    app: botcrew-redis
