apiVersion: v1
kind: ConfigMap
metadata:
  name: botcrew-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "botcrew.labels" . | nindent 4 }}
data:
  BOTCREW_K8S_NAMESPACE: {{ .Values.namespace | quote }}
  BOTCREW_DEBUG: "true"
  BOTCREW_API_PREFIX: "/api/v1"
  BOTCREW_REDIS_URL: "redis://botcrew-redis:{{ .Values.redis.port }}/0"
